New scan path parser and calculator
Rombur/adamantine pull request #65
Opened 2020-09-15 19:52 UTC by stvdwtt

This reads in a scan path segment file using the syntax that is used for OpenFOAM-AM and Thesis at the MDF. Until the new heat source code is added this is free-floating in the code and cannot be used for actual simulations.

2020-09-15 20:59 UTC, Rombur requested changes
This looks pretty good. I have a few comments but most of them are cosmetic. There are two things we need to talk about:
1. Should `ScanPath` derive from `dealii::Function`? A big part of the reason `ElectronBeam` derive from `dealii::Function` is because I wanted to use `dealii::FunctionParser`.
2. Shouldn't we use 3D points for the segments instead of 2D points? Here I am mainly thinking about the case where we have multiple layers.

2020-09-15 20:59 UTC, Rombur commented on source/ElectronBeam.cc
> +    */
Just remove the commented code.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +#define SCAN_PATH_TEMPLATES_HH
You don't need the `ifndef` in the `.cc` I know it exists in a couple of files but there are left over from a code refactor. They shouldn't be there.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +#include <instantiation.hh>
You don't need this. This file only contains macros that can be used for explicit instantiations.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +using std::pow;
You don't need this.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +    std::cout << line << std::endl;
Leftover from debugging?

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +          throw std::runtime_error(message);
Just use ```ASSERT_THROW(false, "Error: Scan paths must begin with a 'point' segment.");```

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +        throw std::runtime_error(message);
Same comment as above.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +    double time, dealii::Point<2> &segment_start_point,
Why is the `Point` 2D? Should it be 2D or 3D depending on the dimensionality of the domain?

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +  if (time > _segment_list[_current_segment].end_time)
I don't think the `if` is necessary here. If the condition is false, you won't get in the `while` loop anyway.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +                       unsigned int const component) const
Is there a point in deriving from `dealii::Function` anymore? You force `component == 1` and it is strange to store the `time` in a `dealii::Point`.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.cc
> +  // scan path coordinates.
I am not sure what you mean here? What's the difference between the global coordinate and the scan path coordinate?

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.hh
> +#include <utils.hh>
You probably don't need this.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.hh
> +  dealii::Point<2> end_point; // Unit: m (NOTE: converted from mm in the file)
Why is this only a 2D point? Shouldn't this be a 3D point? I guess it is fine for now but we won't we need to change this when we have multiple layer?

2020-09-15 20:59 UTC, Rombur commented on tests/CMakeLists.txt
> +     test_scan_path
Can you move this up so that it is in alphabetical order.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.hh
> +  void save_time();
Yeah I don't think this is necessary. The `save_time` and `rewind_time` are needed for some embedded time stepping methods but there is something in deal.II that takes care of that now.

2020-09-15 20:59 UTC, Rombur commented on source/ScanPath.hh
> +  mutable unsigned int _current_segment;
If we don't derive from `dealii::Function` we don't need this be `mutable` anymore.

2020-09-15 20:59 UTC, Rombur commented on source/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/ScanPath.hh
Can you move this up to before `ThermalOperator.hh`

2020-09-15 20:59 UTC, Rombur commented on source/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/ScanPath.cc
Can you move this up before `ThermalOperator.cc`

2020-09-16 13:58 UTC, stvdwtt commented
Thanks for the detailed review @Rombur. I'll make those changes by our next meeting on Tuesday.

Regarding the two issues in your top comment:
1. Not having ScanPath derive from dealii::Function sounds good to me. At one point I had it that way, but then changed it back in case I was missing something about the reason PointSource derived from it -- but it makes sense that it was for the function parser. I agree that it is cleaner without deriving from dealii::Function.
2. I also waffled back and forth on this. I was thinking that we might want to handle the height of the heat source somewhere else, since I think we want/need it to be on the face of the top-most activated cells. I'm not sure how we want to handle interactions with the mesh -- if we want to change the mesh to match the layer heights or the layer heights to match the mesh. Regardless, I can change the segment ends to 3D points and we can add layers of checks (e.g. that the height monotonically increases) and other processing steps (e.g. determining when a new layer starts, shifting the layer height if need be, etc) later on. How does that sound?

2020-09-16 14:21 UTC, Rombur commented
Sounds good. Thanks.

2020-09-21 14:29 UTC, stvdwtt commented on source/ScanPath.cc
> +    std::cout << line << std::endl;
Correct, I'm deleting it.

2020-09-21 14:34 UTC, stvdwtt commented on source/ScanPath.cc
> +  if (time > _segment_list[_current_segment].end_time)
You are correct, that must be left over from an earlier version -- I'm taking it out.

2020-09-21 19:06 UTC, stvdwtt commented on source/ScanPath.cc
> +  // scan path coordinates.
I think I got it slightly wrong in this comment. The issue is that the z direction in the Goldak heat source model (and the z direction in the EB heat source model in ElectronBeam) is what I'd normally call the y direction in the FE mesh (i.e. index 1 out of 0-2). The two sections of code have the last two indices flipped with respect to one another. This isn't a problem, but it just means that some of the bookkeeping in this section looks a little weird.

I'll clarify the comment.

2020-09-21 19:49 UTC, stvdwtt commented on source/ScanPath.cc
> +    double time, dealii::Point<2> &segment_start_point,
I'm going to make the points in the scan path always 3D. This makes it a direct representation of the scan path in the file (which is 3D). It also leaves the possibility of having a 2D simulation where the isn't directly over the slice in question (the physics of this are a bit iffy, but that's the case for these 2D simulations in general.

2020-09-21 19:50 UTC, stvdwtt commented on source/ScanPath.cc
> +                       unsigned int const component) const
Per the comment below, I'm removing the dealii::Function parent.

2020-09-21 19:51 UTC, stvdwtt commented on source/ScanPath.cc
> +  // scan path coordinates.
Actually, I'm going to kick this to the new HeatSource class. That's where the coordinate rotation should happen.

2020-09-21 19:51 UTC, stvdwtt commented on source/ScanPath.hh
> +  dealii::Point<2> end_point; // Unit: m (NOTE: converted from mm in the file)
Agreed. See comment above.

2020-09-21 19:57 UTC, stvdwtt commented
@Rombur I made the changes we discussed, let me know if you see anything else that should be changed before this can be merged.

2020-09-22 01:48 UTC, Rombur reviewed
This looks good. I just have one comment and one question left.

2020-09-22 01:48 UTC, Rombur commented on source/ScanPath.cc
> +        }
You could just write 
```
 ASSERT_THROW(_segment_list.size() == 0, "Error: Scan paths must begin with a 'point' segment.");
```
and get ride of the `if`

2020-09-22 01:48 UTC, Rombur commented on source/ScanPath.cc
> +        segment_type = ScanPathSegmentType::line;
I am a little bit confused, the error message says that we need to start with a point but then you set the `segment_type` to a line.

2020-09-22 13:34 UTC, stvdwtt commented on source/ScanPath.cc
> +        }
Yes, definitely cleaner that way.

2020-09-22 13:37 UTC, stvdwtt commented on source/ScanPath.cc
> +        segment_type = ScanPathSegmentType::line;
The assertion is to make sure that the segment in question isn't the first segment in the list. If it is the first segment, then having it marked as a line in the input file is a problem (violates the spec) and an exception is thrown. If it isn't the first segment, then it's fine that it is a line segment and the ```segment_type``` is set to point. 

Does that make sense? I added a comment to clarify in the code.

2020-09-22 13:42 UTC, Rombur approved these changes

2020-09-22 13:42 UTC, merged